import type { User } from "../models/UserModel";
import { UserRepository } from "../repositories/userRepository";
import  { UserResponse } from "../models/UserResponse";

export class createUserService {

  constructor(private readonly repository: UserRepository) {}

  async execute(user: User): Promise<UserResponse> {
    if(user.password.length < 6) {
      throw new Error("Password must be at least 6 characters long");
    }

    if(!user.id) throw new Error("User ID should not be provided, it will be generated by the system");

    await this.repository.create(user);
    return new UserResponse(user.id, user.username, user.email, user.fullname);
    
  }
}
